### ISSUE TITLE
Website Fails to load anything but default starting page in Chrome

### ISSUE THREAD

**Issue by TheSixStringSamurai** [bodinaren/maplestory-skills#11]
https://i.imgur.com/W6UQ4fQ.png

That's what everything but the default page when you load the website looks like in Chrome, even with all Adblockers turned off.

**Comment by bodinaren** [comment]
Thank you for taking the time to open an issue!

I'm unable to see this error myself. Could you please answer a few questions that might help me understand what's happening?

1. Well, first of all. Is this still happening?
2. Does it show `<ms-archer ></ms-archer>` in the black box above (right after `<script src="..."></script>`)?
3. Was this the first time you visited the page?
4. Does it also happen in Incognito mode?
5. Open the browsers developer console (press F12) and select the `Console` tab, then reload the page. Can you see any errors there?
6. Which version of Chrome are you using? Windows, Mac or Linux?
7. Can you try in another browser to see if it happens there too?

**Comment by TheSixStringSamurai** [comment]
1 and 2) This is archer: <script src="https://unpkg.com/maplestory-skills@^1/dist/maplestory-skills.js"></script>
<ms-archer ></ms-archer>
 Archer loads fine as this is the default.

This is next one assassin: <script src="https://unpkg.com/maplestory-skills@^1/dist/maplestory-skills.js"></script>
<ms-assassin ></ms-assassin>

The background fails to load like the image I linked for this and all other tabs. Have tried clearing cookies and extensions in case there was some weird conflict there. Same results.

===

3) I visited from a reddit post from https://www.reddit.com/r/MapleStory2/ pointing out your site. I have tried several times to get it to load properly in Chrome. Website loads and works 100% fine in Microsoft Edge.

4) Problem persists in incognito mode.

5) I see nothing in console. 

6) Version 70.0.3538.110 (Official Build) (64-bit) Windows 10 Pro 1803 OS build 17134.286

7) 100% functional in Edge which is only other browser installed at the moment.

**Comment by bodinaren** [comment]
It has now been fixed and released.

Thanks again for taking the time to file an issue!
